services:
  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - backend-db
      - kafka
    environment:
      SPRING_DATASOURCE_USERNAME: ${BACKEND_DATABASE_USER}
      SPRING_DATASOURCE_PASSWORD: ${BACKEND_DATABASE_PASSWORD}

  authorization_server:
    build:
      context: ./authorization_server
    container_name: authorization-server
    ports:
      - "8081:8080"
    depends_on:
      - auth-db
    environment:
      SPRING_DATASOURCE_USERNAME: ${AUTH_DATABASE_USER}
      SPRING_DATASOURCE_PASSWORD: ${AUTH_DATABASE_PASSWORD}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}

  notification_service:
    build:
      context: ./notification_service
    container_name: notification-service
    ports:
      - "8082:8080"
    depends_on:
      - notification-db
      - kafka
    environment:
      SPRING_DATASOURCE_USERNAME: ${NOTIFICATION_DATABASE_USER}
      SPRING_DATASOURCE_PASSWORD: ${NOTIFICATION_DATABASE_PASSWORD}

  backend-db:
    image: postgres:15
    container_name: backend-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: backend_db
      POSTGRES_USER: ${BACKEND_DATABASE_USER}
      POSTGRES_PASSWORD: ${BACKEND_DATABASE_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/migrations/backend_db:/docker-entrypoint-initdb.d

  auth-db:
    image: postgres:15
    container_name: auth-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: ${AUTH_DATABASE_USER}
      POSTGRES_PASSWORD: ${AUTH_DATABASE_PASSWORD}
    volumes:
      - auth_db_data:/var/lib/postgresql/data
      - ./db/migrations/auth_db:/docker-entrypoint-initdb.d


  notification-db:
    image: postgres:15
    container_name: notification-db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: notification_db
      POSTGRES_USER: ${NOTIFICATION_DATABASE_USER}
      POSTGRES_PASSWORD: ${NOTIFICATION_DATABASE_PASSWORD}
    volumes:
      - notification_db_data:/var/lib/postgresql/data
      - ./db/migrations/notification_db:/docker-entrypoint-initdb.d
  
  kafka:
    image: apache/kafka:3.9.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9091
      KAFKA_LISTENERS: CONTROLLER://localhost:9091,HOST://0.0.0.0:9092,DOCKER://0.0.0.0:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT,HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
      KAFKA_ADVERTISED_LISTENERS: HOST://localhost:9092,DOCKER://kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  db_data:
  auth_db_data:
  notification_db_data: