package com.taskmates.backend.model.enums;

public enum NotificationType {

    PROJECT_CREATED,
    PROJECT_UPDATED,
    PROJECT_ARCHIVED,
    PROJECT_UNARCHIVED,
    PROJECT_DELETED,

    PROJECT_MEMBER_ADDED,
    PROJECT_MEMBER_REMOVED,
    PROJECT_MEMBER_ROLE_CHANGED,
    PROJECT_OWNER_CHANGED,

    PROJECT_INVITATION_SENT,
    PROJECT_INVITATION_ACCEPTED,
    PROJECT_INVITATION_DECLINED,

    TASK_CREATED,
    TASK_UPDATED,
    TASK_DELETED,
    TASK_ASSIGNED,
    TASK_UNASSIGNED,
    TASK_COMPLETED,
    TASK_REOPENED,
    TASK_STATUS_CHANGED,

    DEADLINE_APPROACHING,
    DEADLINE_PASSED,
    DEADLINE_REMINDER,

    COMMENT_ADDED_TO_TASK,
    COMMENT_ADDED_TO_PROJECT,
    
}
